# Generated by Django 6.0.3 on 2026-03-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo (Ej: 2022 - Presente)')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto o Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción de tareas')),
                ('tecnologias', models.CharField(blank=True, help_text='Separadas por comas.', max_length=200, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experiencias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título o Certificado')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Formaciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Proyecto')),
                ('descripcion', models.TextField()),
                ('enlace_github', models.URLField(blank=True, null=True, verbose_name='Enlace de GitHub')),
                ('enlace_sitio', models.URLField(blank=True, null=True, verbose_name='Enlace del Sitio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('tecnologias', models.CharField(help_text='Separadas por comas.', max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
